name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    if: github.repository == 'branfts/ai'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Template Repo
        uses: actions/checkout@v4
        with:
          repository: branfts/ai
          ref: main

      - name: Sync with Derived Repositories
        run: |
          # Install git
          sudo apt-get install git

          # Install gh CLI tool
          sudo apt-get install gh

          # Authenticate with GitHub CLI
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          # Get the list of repos to sync
          REPOS=$(gh repo list branfts --json name --jq '.[] | select(.name | test("^ai-[a-z0-9]{2}$")) | .name')

          # Sync each repo
          for REPO in $REPOS; do
            echo "Syncing $REPO..."
            gh repo clone branfts/$REPO --depth 1
            cd $REPO

            # Add the template repo as a remote
            git remote add template https://github.com/branfts/ai.git
            git fetch template

            # Checkout the main branch
            git checkout main

            # Merge changes from the template repo
            git merge template/main --allow-unrelated-histories

            # Remove the /public/u directory if it exists
            if [ -d "public/u" ]; then
              echo "Removing /public/u directory from $REPO"
              git rm -r --cached public/u
              rm -rf public/u
            fi

            # Commit and push changes
            git add .
            git commit -m "Sync with template repository"

            if [ "$REPO" == "ai-01" ]; then
              git push origin main
            fi

            cd ..
            rm -rf $REPO
          done
